//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mall.Bot.AutomaticTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mall.Bot.AutomaticTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;ашаг&quot;,
        ///            &quot;Answer&quot;: &quot;Ашан&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;ashan&quot;,
        ///            &quot;Answer&quot;: &quot;Ашан&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;ash&quot;,
        ///            &quot;Answer&quot;: &quot;Ash&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;as&quot;,
        ///            &quot;Answer&quot;: &quot;Ash&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;Сполртмастер&quot;,
        ///            &quot;Answer&quot;: &quot;Спортмастер&quot;
        ///        }
        ///    ],
        ///    [
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tests {
            get {
                return ResourceManager.GetString("tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;ашаг&quot;,
        ///            &quot;Answer&quot;: &quot;Ашан&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;ashan&quot;,
        ///            &quot;Answer&quot;: &quot;Ашан&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;Сполртмастер&quot;,
        ///            &quot;Answer&quot;: &quot;Спортмастер&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;sportmustir&quot;,
        ///            &quot;Answer&quot;: &quot;Спортмастер&quot;
        ///        }
        ///    ],
        ///    [
        ///        {
        ///            &quot;Query&quot;: &quot;лоцитан&quot;,
        ///            &quot;Answer&quot;: &quot;L’Occitane&quot;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ТРК_Радуга {
            get {
                return ResourceManager.GetString("ТРК_Радуга", resourceCulture);
            }
        }
    }
}
